// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmprestimoLivros.API.Models;

[Table("Cliente")]
public partial class Cliente
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("cliCPF")]
    [StringLength(14)]
    [Unicode(false)]
    public string CliCpf { get; set; }

    [Column("cliNome")]
    [StringLength(200)]
    [Unicode(false)]
    public string CliNome { get; set; }

    [Column("cliEndereco")]
    [StringLength(200)]
    [Unicode(false)]
    public string CliEndereco { get; set; }

    [Column("cliCidade")]
    [StringLength(100)]
    [Unicode(false)]
    public string CliCidade { get; set; }

    [Column("cliBairro")]
    [StringLength(100)]
    [Unicode(false)]
    public string CliBairro { get; set; }

    [Column("cliNumero")]
    [StringLength(50)]
    [Unicode(false)]
    public string CliNumero { get; set; }

    [Column("cliTelefoneCelular")]
    [StringLength(14)]
    [Unicode(false)]
    public string CliTelefoneCelular { get; set; }

    [Column("cliTelefoneFixo")]
    [StringLength(13)]
    [Unicode(false)]
    public string CliTelefoneFixo { get; set; }

    [Column("cliInativo")]
    [StringLength(14)]
    [Unicode(false)]
    public int CliInativo { get; set; }

    [InverseProperty("LceIdClienteNavigation")]
    public virtual ICollection<LivroClienteEmprestimo> LivroClienteEmprestimos { get; set; } = new List<LivroClienteEmprestimo>();
}